---
- name: Add Gluu Server Development Repo
  apt_repository:
    repo: deb https://repo.gluu.org/ubuntu/ trusty-devel main
    state: present
    filename: gluu-repo
  when: (ansible_distribution == "Ubuntu" and ansible_distribution_major_version == "14")

- name: Add Gluu Server Development Repo
  apt_repository:
    repo: deb https://repo.gluu.org/ubuntu/ xenial-devel main
    state: present
    filename: gluu-repo
  when: (ansible_distribution == "Ubuntu" and ansible_distribution_major_version == "16")

- name: Add the Repo Apt Key
  apt_key:
    url: https://repo.gluu.org/ubuntu/gluu-apt.key
    state: present

- name: Install Gluu Server 2.4.4
  apt:
    name: gluu-server-2.4.4
    state: latest
    force: yes
    update_cache: yes
  notify: start gluu-server
